name: Build Grammars

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Checkout grammars-v4
        uses: actions/checkout@v6
        with:
          repository: antlr/grammars-v4
          path: lib/grammars-v4
          fetch-depth: 1

      - name: Download ANTLR jar
        run: wget https://www.antlr.org/download/antlr-4.13.2-complete.jar -O
          lib/antlr-4.13.2-complete.jar
      - run: |
          ls -lh
          ls ./lib -lh
      - name: Build antlr language
        run: npm run build:antlr-language

      - name: Build tree-sitter
        run: npm run build:tree-sitter
